[tool.poetry]
version =  "1.0.0"

[tool.semantic_release]
version_variable = [
    "pyproject.toml:version"
]
version_source = "tag"
upload_to_pypi = false
upload_to_release = false
commit_subject = "chore(release): {version}  [skip actions]"
