- name: Set globally available environment variables and ansible facts
  tags:
    - always
  ansible.builtin.include_tasks:
    file: facts.yml
    apply:
      tags:
        - always

- name: Create ~/opt directory if it does not exist
  tags:
    - always
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/opt/"
    state: directory
    mode: '0755'

- name: Install apt packages
  tags:
    - apt
  ansible.builtin.include_tasks:
    file: apt.yml
    apply:
      tags:
        - apt

- name: Update installed apt packages
  when: deb_arch == "amd64"  # FIXME Jetson can't `apt upgrade` (break Docker filesystem as result)
  tags:
    - apt
  ansible.builtin.include_tasks:
    file: apt-upgrade.yml
    apply:
      tags:
        - apt

- name: Install Nvidia GPU drivers and tools
  tags:
    - apt
  when:
    - tapway_gpu_var == "gpu"
    - not nvidia_driver
  ansible.builtin.include_tasks:
    file: gpu.yml
    apply:
      tags:
        - apt

- name: Install and configure shell history search
  when: deb_arch == "amd64"
  tags:
    - dev
  ansible.builtin.include_tasks:
    file: hstr.yml
    apply:
      tags:
        - dev

- name: Customize bash configuration
  tags:
    - dev
  ansible.builtin.include_tasks:
    file: bashrc.yml
    apply:
      tags:
        - dev

- name: Setup Docker
  tags:
    - docker
  ansible.builtin.include_tasks:
    file: docker.yml
    apply:
      tags:
        - docker

- name: Update Docker Compose
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version is ansible.builtin.version('18.04')
  tags:
    - docker-compose
  ansible.builtin.include_tasks:
    file: update-docker-compose.yml
    apply:
      tags:
        - docker-compose

- name: Setup AWS Greengrass
  tags:
    - gg
  ansible.builtin.include_tasks:
    file: gg.yml
    apply:
      tags:
        - gg

- name: Install Haikang camera MVS
  tags:
    - mvs
  ansible.builtin.include_tasks:
    file: mvs.yml
    apply:
      tags:
        - mvs


- name: Install Manager service compose stack
  tags:
    - manager
  ansible.builtin.include_tasks:
    file: manager.yml
    apply:
      tags:
        - manager

- name: Setup Portainer
  tags:
    - portainer
    - dev
  ansible.builtin.include_tasks:
    file: portainer.yml
    apply:
      tags:
        - portainer
