network:
  version: 2
  renderer: networkd
  ethernets:
    {{ interface.stdout }}:
      dhcp4: no
      addresses: ["{{ ip.stdout }}"]
      routes:
        - to: 0.0.0.0/0
          via: "{{ gateway.stdout }}"
      nameservers:
          addresses: [8.8.8.8,8.8.4.4]
