on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.AUTOMATION_DOCKER_HUB_USER }}
          password: ${{ secrets.AUTOMATION_DOCKER_HUB_PASS }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            gotapway/ansible-role-edge-server:${{  github.ref_name }}
            gotapway/ansible-role-edge-server:latest
